approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

npmMinimalAgeGate: 0

# === ADD THIS TO THE BOTTOM ===
packageExtensions:
  "@nestjs/cli@*":
    dependencies:
      commander: "*"